---
title: "high-r-sq-model.rmd"
author: "Avinash Tiwari"
date: '2022-07-30'
output:
  pdf_document: default
  html_document: default
---
# Analysis Workbook
## Proposal
## Define Helper Functions
## EDA

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
options(scipen = 1, digits = 4, width = 80, fig.alin = "center")
```


```{r}
# set seed
#set.seed(11)
set.seed(420072022)
# Load libraries 
library(ggplot2)
library(faraway)
library(lmtest)
```


```{r}
ca_housing_data = read.csv('../000_Data/california-housing-prices/housing.csv')
ca_housing_data = subset(ca_housing_data, 
                         subset = ca_housing_data$ocean_proximity != "ISLAND")
#head(ca_housing_data)
#View(ca_housing_data)
#str(ca_housing_data)
```


```{r}
# delete rows with missing values - as only 207 rows have missing value for only one variable "total_bedrooms"
nrow(ca_housing_data)
cah_data = na.omit(ca_housing_data)
nrow(ca_housing_data) - nrow(cah_data)
```

## Data cleaning

```{r}
cah_trn_idx  = sample(nrow(cah_data), size = trunc(0.70 * nrow(cah_data)))
cah_trn_data = cah_data[cah_trn_idx, ]
cah_tst_data = cah_data[-cah_trn_idx, ]
```

## Variable Creation
```{r}

cah_trn_data$ocean_proximity = as.factor(cah_trn_data$ocean_proximity)
cah_trn_data$pop_per_hh = cah_trn_data$population / cah_trn_data$households
cah_trn_data$rooms_per_hh = cah_trn_data$total_rooms / cah_trn_data$households
cah_trn_data$bedrooms_per_hh = cah_trn_data$total_bedrooms / cah_trn_data$households
```

## Model Building
```{r}

mod  = lm(log(median_house_value) ~ longitude + housing_median_age + median_income + pop_per_hh + bedrooms_per_hh + ocean_proximity, data = cah_trn_data)
#summary(mod)
#vif(mod)
```

```{r}
mod_fix_int = lm (log(median_house_value) ~ (longitude + housing_median_age + median_income + pop_per_hh + bedrooms_per_hh + ocean_proximity ) ^ 2, 
                  data = cah_trn_data, 
                  subset = (cooks.distance(mod) <= 4 /length(cooks.distance(mod))))
summary(mod_fix_int)

```

```{r}
get_RMSE = function(fitted_y, actual_y){
  n = length(fitted_y)                                      #length of data 
  rmse = sqrt((sum(((actual_y - fitted_y) ^ 2)) / n))
}
```

```{r}
cah_tst_data$ocean_proximity = as.factor(cah_tst_data$ocean_proximity)
cah_tst_data$pop_per_hh = cah_tst_data$population / cah_tst_data$households
cah_tst_data$rooms_per_hh = cah_tst_data$total_rooms / cah_tst_data$households
cah_tst_data$bedrooms_per_hh = cah_tst_data$total_bedrooms / cah_tst_data$households

(get_RMSE(predict(mod_fix_int, cah_trn_data), cah_trn_data$median_house_value)) # 237303
(get_RMSE(predict(mod_fix_int, cah_tst_data), cah_tst_data$median_house_value)) # 235732
```



## Model Selection
## Graphs and Tables  
## QA: How do we know what we did makes sense?.
## Move to final report